apiVersion: v1
kind: Secret
metadata:
  name: miniredis-secrets
  namespace: miniredis-dev
type: Opaque
stringData:
  POSTGRES_MAIN_PASSWORD: "change-me"
  POSTGRES_AUTH_PASSWORD: "change-me"
  FIREBASE_API_KEY: "change-me"
  FIREBASE_AUTH_DOMAIN: "change-me"
  FIREBASE_PROJECT_ID: "change-me"
  FIREBASE_STORAGE_BUCKET: "change-me"
  FIREBASE_MESSAGING_SENDER_ID: "change-me"
  FIREBASE_APP_ID: "change-me"
---
apiVersion: v1
kind: Secret
metadata:
  name: firebase-service-account
  namespace: miniredis-dev
type: Opaque
stringData:
  firebase-service-account.json: |
    {}